name: api-tests

on:
  push:
    branches: [ main ]
    # Only run when Python/workflow files change (saves minutes)
    paths:
      - '**/*.py'
      - 'schemas/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
  # Allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    # --- Step 5: Cross-platform matrix (Windows + Linux, multiple Python) ---
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11']

    runs-on: ${{ matrix.os }}
    # Make BASE_URL available to all steps (you set this secret in repo settings)
    env:
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Cache path differs by OS, so split it:
      - name: Cache pip (Linux)
        if: runner.os == 'Linux'
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Cache pip (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run tests and generate HTML report
        # One run that uses BASE_URL env, adds verbose, and produces an artifact
        run: pytest -v --html=report-${{ matrix.os }}-${{ matrix.python-version }}.html --self-contained-html

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: report-*.html
